[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
solc = "0.8.20"

[rpc_endpoints]
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"

[etherscan]
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config